### PR TITLE
Added onlyIfNeeded option

### PR DESCRIPTION
**Pull request by monteiz**
I had a case when I wanted to scroll to the element only if the element was out of the screen, so the `onlyIfNeeded` option has been added.

### CODE REVIEW

**Comment by willhoag** [comment]
Hey @monteiz,

Is there any benefit adding this to the api over wrapping with something like the following?
```
function isVisible(elemRect) {
	var viewHeight = Math.max(document.documentElement.clientHeight, window.innerHeight);
	return !(elemRect.bottom < 0 || elemRect.top - viewHeight >= 0);
}

function scrollToElementIfNeeded (elem, options) {
  if (typeof elem === 'string') elem = document.querySelector(elem);
  return (!isVisible(elem.getBoundingClientRect())
    ? scrollToElement(elem, options)
    : undefined);
}
```

**Comment by monteiz** [comment]
Hey @willhoag,
what would you answer if somebody asked you:

_Is there any benefit using your library over writing something like the following?_

```
var scroll = require('scroll-to');

function calculateScrollOffset(elem, additionalOffset, alignment) {
  var body = document.body,
      html = document.documentElement;

  var elemRect = elem.getBoundingClientRect();
  var clientHeight = html.clientHeight;
  var documentHeight = Math.max( body.scrollHeight, body.offsetHeight, 
                                 html.clientHeight, html.scrollHeight, html.offsetHeight );

  additionalOffset = additionalOffset || 0;

  var scrollPosition;
  if (alignment === 'bottom') {
    scrollPosition = elemRect.bottom - clientHeight;
  } else if (alignment === 'middle') {
    scrollPosition = elemRect.bottom - clientHeight / 2 - elemRect.height / 2;
  } else { // top and default
    scrollPosition = elemRect.top;
  }

  var maxScrollPosition = documentHeight - clientHeight;
  return Math.min(scrollPosition + additionalOffset + window.pageYOffset,
                  maxScrollPosition);
}

module.exports = function (elem, options) {
  options = options || {};
  if (typeof elem === 'string') elem = document.querySelector(elem);
  if (elem) return scroll(0, calculateScrollOffset(elem, options.offset, options.align), options);
};
```

**Comment by willhoag** [comment]
In this case, no because it's already the exact same code as the library. Use the library.

To be honest, I'm just trying to explore if this is a good fit for general use case of the package. Your usage seems like an edge case to me and I was looking for more details to confirm or deny.

Right now the API has no conditional logic in it, which makes it very straightforward. This PR would change that.

ATM, this feels like it's a good opportunity for a fork or as a wrapping/composed function.

**Comment by monteiz** [comment]
> To be honest, I'm just trying to explore if this is a good fit for general use case of the package. Your usage seems like an edge case to me and I was looking for more details to confirm or deny.

This is so far from being an edge case.

This is the behaviour you want in **every** form: on submit, one of the field is not valid, so it gets highlighted, but it is not in the visible area of the browser. Obviously the application needs to scroll up to the field to make it visible, to show the user why the submit failed. But if the field is already in the visible area of the browser, you do not want the application to scroll.

This is why it even exists a dedicated function implemented by Firefox and Chrome for exactly this purpose: [scrollIntoViewIfNeeded()](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoViewIfNeeded). Problem is, this function does not scroll at all: it just moves the visible area in 0ms, which creates a very poor user experience.

With the `onlyIfNeeded` option, this library would fill this gap, giving the community a single and simple solution that covers all the cases.

Feel free to close this PR. Thanks anyway for your library, it works very well.

**Comment by Reloecc** [comment]
This happened over a year ago, so it doesn't matter now, but for real, Mr. willhoag, you are a piece of a stubborn folk :)). Having a feature served on the golden plate, without conflicts, and you are not willing to accept it even if it's a single click? That's.. impressive.

**Pull request closed without merging**
